"use client"


import { Editor, Viewer } from '@bytemd/react'
import pluginGfm from '@bytemd/plugin-gfm'
import { useMemo, useState } from 'react'
import { Box, Button, HStack, Input } from '@chakra-ui/react'

export const metadata = {
  title: 'Markdown Editor',
  description: 'Generated by create next app',
}

export default function MDEditor() {
  const [value, setValue] = useState('')
  const plugins = useMemo(() => [pluginGfm()], [])

  return (
    <Box pb='1' px='2'>
      <HStack h="56px">
        <Input variant="filled" placeholder="请输入标题" />
        <Button colorScheme="twitter">保存</Button>
      </HStack>
      <Editor
        value={value}
        plugins={plugins}
        onChange={(v) => {
          setValue(v)
        }}
      />
    </Box>
  )
}
