"use client"

import { Inter } from 'next/font/google'
import { Container, List } from '@chakra-ui/react'
import styles from './page.module.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <Container as="main">
      
    </Container>
  )
}
